# Generated by Django 3.0.7 on 2020-09-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200905_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diversity_program', models.CharField(max_length=100, null=True)),
                ('diversity_link', models.CharField(max_length=100, null=True)),
                ('diversity_industry', models.CharField(max_length=100, null=True)),
                ('diversity_population', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
