# Generated by Django 3.0.7 on 2020-09-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_internships_programs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Internships',
            new_name='Internship',
        ),
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
