# Generated by Django 3.0.7 on 2020-09-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200909_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
    ]
