# Generated by Django 3.0.7 on 2020-09-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
