# Generated by Django 3.0.7 on 2020-09-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_admin_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='admin_approved',
        ),
        migrations.AddField(
            model_name='internship',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
