# Generated by Django 3.0.7 on 2020-09-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20200927_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='eventDate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='eventName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
