# Generated by Django 3.0.7 on 2020-09-29 19:01

from django.db import migrations, models
import trix.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_resource_content2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', trix.fields.TrixField(verbose_name='Content')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='content2',
        ),
    ]
