# Generated by Django 3.0.7 on 2020-10-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_postimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='admin_approved',
            field=models.BooleanField(default=True),
        ),
    ]
