# Generated by Django 3.0.7 on 2020-10-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20201002_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32, null=True)),
                ('info', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='profile_pics')),
            ],
        ),
    ]
