# Generated by Django 3.0.7 on 2020-10-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classof',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
