# Generated by Django 3.0.7 on 2020-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_profile_classof'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('major', models.CharField(max_length=1000, null=True)),
                ('classof', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('funfact', models.CharField(max_length=1000, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
