# Generated by Django 3.0.7 on 2020-10-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20201003_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredstudent',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
