# Generated by Django 3.0.7 on 2020-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20201003_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredstudent',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
