# Generated by Django 3.0.7 on 2020-10-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('eventName', models.CharField(blank=True, max_length=1000, null=True)),
                ('eventDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('admin_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.Gallery', verbose_name='Gallery')),
            ],
        ),
    ]
