# Generated by Django 3.0.7 on 2020-10-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.Gallery', verbose_name='Gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryImages',
        ),
    ]
